### ISSUE TITLE
Improve description?

### ISSUE THREAD

**Issue by impressivewebs** [atayahmet/jquery.easypin#1]
Very nice plugin! I'll be [adding it to my newsletter this week](http://webtoolsweekly.com/). One thing I wanted to point out is that the description is a little confusing. Instead of saying "image pinning plugin", it would be better to use the description from the top of the repo, where it says "pinning objects on pictures".

If you say "image pinning" that sounds like you're pinning the image to the page (kind of like fixed positioning something in CSS). Better to say "pinning clickable messages/notes to images" or something like that. But overall, great job!

**Comment by atayahmet** [comment]
Hi impressivewebs,

I'm sorry for the late reply. Thank you for detailed comments and newsletters. I will change description as soon as possible.
